### ISSUE TITLE
[BUG] The profile name is not quoted when used

### ISSUE THREAD

**Issue by jfp42** [paddywaan/HandBrake-daemon#3]
If you have a profile name like "High Profile Bluray mkv strong"
Then the command line supplied looks like this
--preset-import-file "/home/BLAH//High Profile Bluray mkv strong x265.json" -Z High Profile Bluray mkv strong x265 

It should be 
--preset-import-file "/home/BLAH//High Profile Bluray mkv strong x265.json" -Z "High Profile Bluray mkv strong x265"

PS: Thanks for this project.

**Comment by paddywaan** [comment]
Thanks for reporting this, I am glad you find this project to be of use!
